baseURL = "https://www.quiethacker.com/"
title = "quiethacker.com"

languageCode = "en-us"
theme = "ChoNormal"
dateFormat = "2006年01月02日"
disqusShortname = "quiethacker"

[Params]
    author = "quiethacker"
    images = ["images/featured.jpg"]
    description ="the quiet hacker's archive"
    tags = ""
    

[outputs]
  page = ["HTML" , "RSS"]
  Home = ["HTML" , "RSS"]


[taxonomies]
    tag = "tags"
    archive = "archives"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false
